In [1]:
import numpy as np
import pandas as pd
from collections import Counter


In [2]:
df=pd.read_csv("dataset07.csv")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [3]:
df['Category']=df['Category'].map({
    'ham' :0,
    'spam':1
    })

In [23]:
message=[]
for text in df['Message']:
    text=text.lower()
    words=text.split()
    message.append(words)
labels=list(df["Category"])


In [24]:
vocab=sorted(set(
    word
    for sentence in message
    for word in sentence
))

print("Vocab size =",len(vocab))

Vocab size = 13574


In [25]:
#bag of words
#bow function
def bow_vector(sentence,vocab):
    vector=[]
    word_count=Counter(sentence)
    for word in vocab:
        vector.append(word_count[word])
    return vector

In [26]:
bow_vectors=[]
for sentence in message[:5]:
    vec=bow_vector(sentence,vocab)
    bow_vectors.append(vec)
    print("Sentence")
    print(sentence)
    print(sum(vec))
    print("BoW vector")
    print(vec[:20])

Sentence
['go', 'until', 'jurong', 'point,', 'crazy..', 'available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet...', 'cine', 'there', 'got', 'amore', 'wat...']
20
BoW vector
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Sentence
['ok', 'lar...', 'joking', 'wif', 'u', 'oni...']
6
BoW vector
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Sentence
['free', 'entry', 'in', '2', 'a', 'wkly', 'comp', 'to', 'win', 'fa', 'cup', 'final', 'tkts', '21st', 'may', '2005.', 'text', 'fa', 'to', '87121', 'to', 'receive', 'entry', 'question(std', 'txt', "rate)t&c's", 'apply', "08452810075over18's"]
28
BoW vector
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Sentence
['u', 'dun', 'say', 'so', 'early', 'hor...', 'u', 'c', 'already', 'then', 'say...']
11
BoW vector
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Sentence
['nah', 'i', "don't", 'think', 'he', 'goes', 'to', 'usf,', 'he', 'lives', 'around', 'here', 'though']
13
BoW 

In [31]:
#TF-IDF

N=len(message)

dfeq={}
for word in vocab:
    count=0
    for sentence in message:
        if word in sentence:
            count+=1
    dfeq[word]=count

In [32]:
idf={}
for word in vocab:
    idf[word]=np.log(N/dfeq[word])

In [33]:
def tfidf_vector(sentence):
    word_count=Counter(sentence)
    sentence_len=len(sentence)
    vector=[]
    for word in vocab:
        tf=word_count[word]/sentence_len
        tfid=tf*idf[word]
        vector.append(tfid)
    return vector

In [36]:
print("TF-IDF vectors")
for sentence in message[:3]:
    vec=tfidf_vector(sentence)
    print(sentence)
    print(vec[:20])

TF-IDF vectors
['go', 'until', 'jurong', 'point,', 'crazy..', 'available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet...', 'cine', 'there', 'got', 'amore', 'wat...']
[np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0)]
['ok', 'lar...', 'joking', 'wif', 'u', 'oni...']
[np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0)]
['free', 'entry', 'in', '2', 'a', 'wkly', 'comp', 'to', 'win', 'fa', 'cup', 'fina

In [37]:
embedding_size=5
word_embedding={}
for word in vocab:
    word_embedding[word]=np.random.rand(embedding_size)

In [38]:
def sentence_vector(sentence):
    vectors=[]
    for word in sentence:
        vectors.append(word_embedding[word])
    return np.mean(vectors,axis=0)

In [41]:
print("\nWORD2VEC REPRESENTATION\n")

for sentence in message[:3]:
    vec = sentence_vector(sentence)
    print(sentence)
    print(vec)


WORD2VEC REPRESENTATION

['go', 'until', 'jurong', 'point,', 'crazy..', 'available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet...', 'cine', 'there', 'got', 'amore', 'wat...']
[0.41535643 0.48907547 0.48577531 0.63475196 0.53322246]
['ok', 'lar...', 'joking', 'wif', 'u', 'oni...']
[0.35683518 0.41942141 0.37555746 0.32808009 0.61713624]
['free', 'entry', 'in', '2', 'a', 'wkly', 'comp', 'to', 'win', 'fa', 'cup', 'final', 'tkts', '21st', 'may', '2005.', 'text', 'fa', 'to', '87121', 'to', 'receive', 'entry', 'question(std', 'txt', "rate)t&c's", 'apply', "08452810075over18's"]
[0.4790113  0.46688561 0.48598513 0.41514387 0.51411425]


In [42]:
spam_words=[]
ham_words=[]
for sentence,label in zip(message,labels):
    if label==1:
        spam_words.extend(sentence)
    else:
        ham_words.extend(sentence)

In [43]:
spam_count = Counter(spam_words)
ham_count = Counter(ham_words)

In [44]:
def predict(sentence):

    sentence = sentence.lower().split()

    spam_score = 1
    ham_score = 1

    for word in sentence:

        spam_score *= (spam_count[word] + 1)

        ham_score *= (ham_count[word] + 1)

    if spam_score > ham_score:
        return "SPAM"

    return "HAM"

In [46]:
test = "Free prize you have to claim now"

result = predict(test)

print("\nTest Message =", test)

print("Prediction =", result)


Test Message = Free prize you have to claim now
Prediction = SPAM
